# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
language: "en-US"
tone_instructions: "Be brief."

# =============================================================================
# REVIEWS
# =============================================================================
reviews:
  profile: "assertive"
  # Approve the review once CodeRabbit’s comments are resolved
  # and no pre-merge checks are in an error state.
  request_changes_workflow: true
  # Generate a high level summary of the changes in the PR/MR description.
  high_level_summary: false
  # Include the high level summary in the walkthrough comment.
  high_level_summary_in_walkthrough: false
  # Post review details on each review. Additionally, post a review status when a review is skipped in certain cases.
  review_status: true
  # Set the commit status to 'pending' when the review is in progress and 'success' when it is complete.
  commit_status: true
  # Set the commit status to 'failure' when the PR cannot be reviewed by CodeRabbit for any reason.
  fail_commit_status: true
  # Generate walkthrough in a markdown collapsible section.
  collapse_walkthrough: true
  # Generate a summary of the changed files in the walkthrough.
  changed_files_summary: false
  # Generate sequence diagrams in the walkthrough.
  sequence_diagrams: false
  # Estimate the code review effort in the walkthrough.
  estimate_code_review_effort: true
  # Generate an assessment of how well the changes address the linked issues in the walkthrough.
  assess_linked_issues: false
  # Include possibly related issues in the walkthrough.
  related_issues: false
  # Related PRs - Include possibly related pull requests in the walkthrough.
  related_prs: false
  # Suggest labels based on the changes in the pull request in the walkthrough.
  suggested_labels: false
  # Suggest reviewers based on the changes in the pull request in the walkthrough.
  suggested_reviewers: false
  # Generate a poem in the walkthrough comment.
  poem: false
  # Specify file patterns to include or exclude in a review using glob patterns (e.g., !dist/**, src/**).
  path_filters:
    ["!dist/**", "!build/**", "!bin/**", "!out/**", "!node_modules/**"]

  # Configuration for auto review
  auto_review:
    # Automatic Review - Automatic code review
    enabled: true
    # Review draft PRs/MRs.
    drafts: false
    # Ignore reviewing if the title of the pull request contains any of these keywords (case-insensitive).
    ignore_title_keywords: ["WIP", "Draft"]

  # LanguageTool is a style and grammar checker for 30+ languages.
  languagetool:
    # Enable LanguageTool - Enable LanguageTool integration.
    enabled: true
    # If set to 'picky', additional rules will be activated, i.e. rules that you might only find useful when checking formal text.
    level: "picky"
