name: PR title & description lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

jobs:
  lint:
    name: Validate PR title and description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = (pr.title || '').trim();
            const body = (pr.body || '').trim();

            const okTitle = /^<(feat|fix|docs)>\s/;
            const okBody = body.length > 0;

            if (!okTitle || !okBody) {
              let msg = '❌ Pull Request validation failed:\n';
              if (!okTitle) {
                msg += `- Title must start with "<feat>", "<fix>", or "<docs>" (lowercase, then a space). Current: "${title}".\n`;
              }
              if (!okBody) {
                msg += `- Description (PR body) must not be empty.\n`;
              }
              core.setFailed(msg);
            } else {
              core.info('✅ PR title and description look good.');
            }
