#pragma once

#include <raylib.h>

#define RENDER_COLOR_BACKGROUND (Color){25, 25, 25, 255}
#define RENDER_COLOR_ALPHA 100
#define RENDER_COLOR_DEBUG \
    (Color) { 255, 255, 255, RENDER_COLOR_ALPHA }
#define RENDER_COLOR_RED \
    (Color) { 255, 0, 0, RENDER_COLOR_ALPHA }
#define RENDER_COLOR_GREEN \
    (Color) { 0, 255, 0, RENDER_COLOR_ALPHA }
#define RENDER_COLOR_BLUE \
    (Color) { 0, 0, 255, RENDER_COLOR_ALPHA }

#define RENDER_DEBUG_INSIGHT_FONT_SIZE 10
#define RENDER_DEBUG_INSIGHT_MARGIN_X 5
#define RENDER_DEBUG_INSIGHT_MARGIN_Y 5
#define RENDER_DEBUG_INSIGHT_SEPARATOR 5